fix setup command
gitbugactions/gitbug-java pull request #14
Opened 2024-01-05 12:21 UTC by andre15silva

2024-01-23 17:57 UTC, Nfsaavedra requested changes
Is this supporting the usage of a specific act-cache? I couldn't find it. Also, we need to close the issues that are already handled, we have to take a look at that.

2024-01-23 17:57 UTC, Nfsaavedra commented on gitbug/bug.py
> +                print(f"- {failed_test.classname}#{failed_test.name}")
Here I think we could add some color. For instance, having the "Failed tests:" as red in the shell by using `\033[0;31m `and `\033[0m`. Another thing is that maybe it would be nice to create a json file with this information. I think that makes it easier for someone who wants to build a program with the CLI.

2024-01-23 19:11 UTC, andre15silva commented
> Is this supporting the usage of a specific act-cache? I couldn't find it. Also, we need to close the issues that are already handled, we have to take a look at that.

Not yet, we still need to take care of that actually.

2024-02-05 09:37 UTC, andre15silva commented
@Nfsaavedra ready for review and merge :D

2024-02-05 16:47 UTC, Nfsaavedra approved these changes
We should fix the comments I did but then we can merge. :partying_face:

2024-02-05 16:47 UTC, Nfsaavedra commented on gitbug/bug.py
>              # TODO: use a hardcoded path to act
Is this TODO important?

2024-02-05 16:47 UTC, Nfsaavedra commented on gitbug/bug.py
> +                    ],
Since it is information that we show, we should probably also add the Unexpected tests, Missing tests and Skipped tests here.

2024-02-05 16:47 UTC, Nfsaavedra commented on gitbug/bug.py
> +        #     # logging.debug(run.stdout)
Remove or add only has debug

2024-02-05 16:53 UTC, andre15silva commented on gitbug/bug.py
>              # TODO: use a hardcoded path to act
It is important if we want the command to work from everywhere.

This is not just a problem in this path however, it will happen with others (e.g. the path to the json files)

2024-02-05 16:54 UTC, andre15silva commented on gitbug/bug.py
> +                    ],
Ya, sounds like a good idea.

2024-02-05 16:54 UTC, andre15silva commented on gitbug/bug.py
> +        #     # logging.debug(run.stdout)
Only as debug yes

2024-02-05 18:50 UTC, merged